{
 "title": "Docker monitoring with service selection 2",
 "description": "Docker monitoring with Prometheus and cAdvisor with node and service selection",
 "tags": [
  "docker",
  "cadvisor",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(container_memory_usage_bytes{image!=\"\"}, job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(container_memory_usage_bytes{job=~\"$job\", image!=\"\"}, instance)"
    }
   },
   {
    "name": "name",
    "label": "Service",
    "query": {
     "query": "label_values(container_memory_usage_bytes{job=~\"$job\", image!=\"\", instance=~\"$node\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$node\",job=~\"$job\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"$node\",job=~\"$job\",image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{instance=~\"$node\",job=~\"$job\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{instance=~\"$node\",job=~\"$job\",image!=\"\"}[$__rate_interval]) * 100) "
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{instance=~\"$node\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_user_seconds_total{instance=~\"$node\",job=~\"$job\",image!=\"\", name=~\"$name\"}[$__rate_interval]) ) * 100 ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{instance=~\"$node\",job=~\"$job\",image!=\"\", name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{instance=~\"$node\",job=~\"$job\",image!=\"\", name=~\"$name\"}[$__rate_interval]))",
     "legendFormat": "recv {{name}}"
    },
    {
     "expr": "-(sum by (name) (rate(container_network_transmit_bytes_total{instance=~\"$node\",job=~\"$job\",image!=\"\", name=~\"$name\"}[$__rate_interval])))",
     "legendFormat": "trans {{name}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_fs_reads_bytes_total{instance=~\"$node\",job=~\"$job\",image!=\"\", name=~\"$name\"}[$__rate_interval]))",
     "legendFormat": "read {{name}}"
    },
    {
     "expr": "-(sum by (name) (rate(container_fs_writes_bytes_total{instance=~\"$node\",job=~\"$job\",image!=\"\", name=~\"$name\"}[$__rate_interval])))",
     "legendFormat": "write {{name}}"
    }
   ]
  }
 ]
}